version: '3.8'
services:
  movies:
    image: manoj2395/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: manoj2395/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: manoj2395/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: manoj2395/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
